(cl:defpackage ros_unity_robotics-srv
  (:use )
  (:export
   "JOINTS_STATE_PANDA"
   "<JOINTS_STATE_PANDA-REQUEST>"
   "JOINTS_STATE_PANDA-REQUEST"
   "<JOINTS_STATE_PANDA-RESPONSE>"
   "JOINTS_STATE_PANDA-RESPONSE"
   "SETCOLOR"
   "<SETCOLOR-REQUEST>"
   "SETCOLOR-REQUEST"
   "<SETCOLOR-RESPONSE>"
   "SETCOLOR-RESPONSE"
   "TRAJECTORY_PLANNER_ROBOT"
   "<TRAJECTORY_PLANNER_ROBOT-REQUEST>"
   "TRAJECTORY_PLANNER_ROBOT-REQUEST"
   "<TRAJECTORY_PLANNER_ROBOT-RESPONSE>"
   "TRAJECTORY_PLANNER_ROBOT-RESPONSE"
  ))

