// Generated by gencpp from file ros_unity_robotics/Joints_State_PandaRequest.msg
// DO NOT EDIT!


#ifndef ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDAREQUEST_H
#define ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_unity_robotics
{
template <class ContainerAllocator>
struct Joints_State_PandaRequest_
{
  typedef Joints_State_PandaRequest_<ContainerAllocator> Type;

  Joints_State_PandaRequest_()
    : name()  {
    }
  Joints_State_PandaRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Joints_State_PandaRequest_

typedef ::ros_unity_robotics::Joints_State_PandaRequest_<std::allocator<void> > Joints_State_PandaRequest;

typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaRequest > Joints_State_PandaRequestPtr;
typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaRequest const> Joints_State_PandaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_unity_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f2d21c30868b92dc41a0431bacd47b2";
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f2d21c30868b92dULL;
  static const uint64_t static_value2 = 0xc41a0431bacd47b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_unity_robotics/Joints_State_PandaRequest";
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
;
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joints_State_PandaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_unity_robotics::Joints_State_PandaRequest_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDAREQUEST_H
