// Generated by gencpp from file ros_unity_robotics/Joints_State_PandaResponse.msg
// DO NOT EDIT!


#ifndef ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDARESPONSE_H
#define ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_unity_robotics
{
template <class ContainerAllocator>
struct Joints_State_PandaResponse_
{
  typedef Joints_State_PandaResponse_<ContainerAllocator> Type;

  Joints_State_PandaResponse_()
    : found()
    , position()  {
    }
  Joints_State_PandaResponse_(const ContainerAllocator& _alloc)
    : found(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _found_type;
  _found_type found;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Joints_State_PandaResponse_

typedef ::ros_unity_robotics::Joints_State_PandaResponse_<std::allocator<void> > Joints_State_PandaResponse;

typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaResponse > Joints_State_PandaResponsePtr;
typedef boost::shared_ptr< ::ros_unity_robotics::Joints_State_PandaResponse const> Joints_State_PandaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.found == rhs.found &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_unity_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "785adb81720cc9e50d19b610dc028963";
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x785adb81720cc9e5ULL;
  static const uint64_t static_value2 = 0x0d19b610dc028963ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_unity_robotics/Joints_State_PandaResponse";
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] found\n"
"float64[] position\n"
"\n"
;
  }

  static const char* value(const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joints_State_PandaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_unity_robotics::Joints_State_PandaResponse_<ContainerAllocator>& v)
  {
    s << indent << "found[]" << std::endl;
    for (size_t i = 0; i < v.found.size(); ++i)
    {
      s << indent << "  found[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.found[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_UNITY_ROBOTICS_MESSAGE_JOINTS_STATE_PANDARESPONSE_H
