// Generated by gencpp from file ros_unity_robotics/SetColorRequest.msg
// DO NOT EDIT!


#ifndef ROS_UNITY_ROBOTICS_MESSAGE_SETCOLORREQUEST_H
#define ROS_UNITY_ROBOTICS_MESSAGE_SETCOLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_unity_robotics
{
template <class ContainerAllocator>
struct SetColorRequest_
{
  typedef SetColorRequest_<ContainerAllocator> Type;

  SetColorRequest_()
    : object_name()  {
    }
  SetColorRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetColorRequest_

typedef ::ros_unity_robotics::SetColorRequest_<std::allocator<void> > SetColorRequest;

typedef boost::shared_ptr< ::ros_unity_robotics::SetColorRequest > SetColorRequestPtr;
typedef boost::shared_ptr< ::ros_unity_robotics::SetColorRequest const> SetColorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator1> & lhs, const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_unity_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_unity_robotics/SetColorRequest";
  }

  static const char* value(const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n"
;
  }

  static const char* value(const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetColorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_unity_robotics::SetColorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_unity_robotics::SetColorRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_UNITY_ROBOTICS_MESSAGE_SETCOLORREQUEST_H
