// Generated by gencpp from file ros_unity_robotics/SetColor.msg
// DO NOT EDIT!


#ifndef ROS_UNITY_ROBOTICS_MESSAGE_SETCOLOR_H
#define ROS_UNITY_ROBOTICS_MESSAGE_SETCOLOR_H

#include <ros/service_traits.h>


#include <ros_unity_robotics/SetColorRequest.h>
#include <ros_unity_robotics/SetColorResponse.h>


namespace ros_unity_robotics
{

struct SetColor
{

typedef SetColorRequest Request;
typedef SetColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetColor
} // namespace ros_unity_robotics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_unity_robotics::SetColor > {
  static const char* value()
  {
    return "fbf49a4abb8329015706cddfa8925046";
  }

  static const char* value(const ::ros_unity_robotics::SetColor&) { return value(); }
};

template<>
struct DataType< ::ros_unity_robotics::SetColor > {
  static const char* value()
  {
    return "ros_unity_robotics/SetColor";
  }

  static const char* value(const ::ros_unity_robotics::SetColor&) { return value(); }
};


// service_traits::MD5Sum< ::ros_unity_robotics::SetColorRequest> should match
// service_traits::MD5Sum< ::ros_unity_robotics::SetColor >
template<>
struct MD5Sum< ::ros_unity_robotics::SetColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_unity_robotics::SetColor >::value();
  }
  static const char* value(const ::ros_unity_robotics::SetColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_unity_robotics::SetColorRequest> should match
// service_traits::DataType< ::ros_unity_robotics::SetColor >
template<>
struct DataType< ::ros_unity_robotics::SetColorRequest>
{
  static const char* value()
  {
    return DataType< ::ros_unity_robotics::SetColor >::value();
  }
  static const char* value(const ::ros_unity_robotics::SetColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_unity_robotics::SetColorResponse> should match
// service_traits::MD5Sum< ::ros_unity_robotics::SetColor >
template<>
struct MD5Sum< ::ros_unity_robotics::SetColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_unity_robotics::SetColor >::value();
  }
  static const char* value(const ::ros_unity_robotics::SetColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_unity_robotics::SetColorResponse> should match
// service_traits::DataType< ::ros_unity_robotics::SetColor >
template<>
struct DataType< ::ros_unity_robotics::SetColorResponse>
{
  static const char* value()
  {
    return DataType< ::ros_unity_robotics::SetColor >::value();
  }
  static const char* value(const ::ros_unity_robotics::SetColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_UNITY_ROBOTICS_MESSAGE_SETCOLOR_H
